# Uncomment this line to define a global platform for your project
platform :ios, "7.1"
pod 'AFNetworking', '~> 2.2'
pod 'EGOTableViewPullRefresh', '~> 0.1.0'

#target "RottenTomatoes" do
#
#end
#
#target "RottenTomatoesTests" do
#
#end
#
