# Uncomment this line to define a global platform for your project
platform :ios, "7.1"
pod 'AFNetworking', '~> 2.2'
pod 'EGOTableViewPullRefresh', '~> 0.1.0'
pod 'MBProgressHUD', '~> 0.5'
pod 'CSNotificationView', '~> 0.4.2'

#target "RottenTomatoes" do
#
#end
#
#target "RottenTomatoesTests" do
#
#end
#
